### PR TITLE
Added ability to configure non-default install location

### PR DESCRIPTION
**Pull request by WilliamWsyHK**
Just as my commit description. Hope you and others enjoy!

### CODE REVIEW

**Comment by TypicalFooBar** [comment]
Hey, this looks as easy as you described on steam! I'll test this tonight and if all looks good I'll merge it in and push an update to the workshop. I need to also update the documentation to show the users how they can set the steamLibraryPrefix variable in the app.config file.

Out of curiosity, have you tested this with your steam games installed on a separate hard drive (like E:/)?

Thanks for this! 👍

**Comment by WilliamWsyHK** [comment]
Yes I tested before creating this PR

**Comment by TypicalFooBar** [comment]
Okay, that's perfect; I'll test tonight and then merge/push to the workshop.

Thank you!

**Comment by WilliamWsyHK** [comment]
For the record, I have also just found if we could use RegKey to recognize this value
For x64 Machines, the RegKey is located at
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 287450
and there is a key "InstallLocation"!!!!! :point_left::point_up: Yes the target!

Unfortunately I think I will not write this code myself as I am not familiar with touching RegKey in C#, but just my bare hand... but it should be the good start for a better bullet-proof way to do this.

**Comment by TypicalFooBar** [comment]
Interesting. I haven't worked with the registry much, either, but I think I'll look at it for a bit tonight as well.

Even if the registry thing does work out, I think it'd be good to have this variable available in the app.config like you've done. This way the user can have complete control over where the code looks for the steam apps. It's a good backup plan to override the program's guess at where the steam apps are on the computer :P

**Comment by TypicalFooBar** [comment]
I didn't have time to do this the other night, but I did just now; I'm merging this and uploading it to the workshop.

Thanks again for your contribution! If there is other stuff you'd like to do with this project, I can add you as a collaborator to this repo. :)

**Comment by WilliamWsyHK** [comment]
Thanks for the collaborator title here.

Just for the record, deleted my fork and in case if I change the code, I would just create a branch for merge, and review via the same branch.

**Pull request merged**
